config:
  send_anonymous_usage_stats: False

supercell:
  target: default
  outputs:
    default:
      type: clickhouse
      schema: rightsize           # Your database/schema name
      host: 3.108.206.137
      port: 8123
      user: default
      password: default
      database: rightsize         # Required for ClickHouse